"""Parser tests against real archived pages.

    python tests/test_parsers.py

WHY THESE EXIST
---------------
37% of claims in the store were parsed heuristically out of summary tables and
free text. Nothing checked that the parser read them correctly, and the first
thing a careful read of four pages turned up was that 250 of 544 Indian MPs were
silently missing their declared criminal-case count: the "Crime-O-Meter" block
writes the number AFTER the words ("Number of Criminal Cases: 88") and the regex
only matched a leading-number form that never appears on the page. Members with
zero cases parsed fine; every member WITH cases recorded no data at all.

That is the worst possible direction for an error in a tool like this - it made
the dataset look cleaner than reality - and it survived a full 543-member harvest
without a single visible symptom.

THE RULE FOR THIS FILE
----------------------
Expected values are read BY EYE from the rendered page and written down here by
hand. They are never generated by running the parser. A test whose expectations
came from the code under test proves only that the code is deterministic.

Each fixture is a real archived document, byte-identical to what the harvester
saw, so these tests also pin the page layouts we depend on: if MyNeta restructures
its pages, a fresh fixture will fail against these hand-read values and tell us.
"""

from __future__ import annotations

import json
import sqlite3
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from ingest.extractors.myneta import MyNeta, rupees  # noqa: E402
from ingest.extractors.ukparliament import UKParliament, sterling  # noqa: E402
from ingest.schema import connect  # noqa: E402

FIX = Path(__file__).parent / "fixtures"

failures: list[str] = []


def check(name: str, got, want) -> None:
    ok = got == want
    print(f"  {'PASS' if ok else 'FAIL'}  {name}"
          + ("" if ok else f"\n          got  {got!r}\n          want {want!r}"))
    if not ok:
        failures.append(name)


# ---------------------------------------------------------------------------
# Hand-read expectations. Every value below was read off the rendered page.
# ---------------------------------------------------------------------------

MYNETA_EXPECTED = {
    "myneta_multi_election.html": {
        # https://www.myneta.info/LokSabha2024/candidate.php?candidate_id=476
        "name": "Amraram",
        "party": "CPI(M)",
        "constituency": "SIKAR",
        "region": "RAJASTHAN",
        "age": 68.0,
        "education_level": "Post Graduate",
        "self_profession": "Agriculture Work and Pension of former MLA",
        "declared_assets_2024": 4050109.0,       # "Assets: Rs 40,50,109"
        "declared_liabilities_2024": None,       # page says "Liabilities: Nil"
        "criminal_cases_2024": 0.0,              # "No criminal cases"
        # "Other Elections" table, read row by row
        "asset_history": {
            2008: 1734392.0,   # Rajasthan 2008   Rs17,34,392
            2009: 1902684.0,   # Lok Sabha 2009   Rs19,02,684
            2013: 4084479.0,   # Rajasthan 2013   Rs40,84,479
            2014: 4681929.0,   # Loksabha 2014    Rs46,81,929
            2018: 4353653.0,   # Rajasthan 2018   Rs43,53,653
            2019: 4444641.0,   # Lok Sabha 2019   Rs44,44,641
            2023: 3842432.0,   # Rajasthan 2023   Rs38,42,432
        },
    },
    "myneta_no_cases.html": {
        # https://www.myneta.info/LokSabha2024/candidate.php?candidate_id=17
        "name": "Bishnu Pada Ray",
        "party": "BJP",
        "constituency": "ANDAMAN AND NICOBAR ISLANDS",
        "region": "ANDAMAN AND NICOBAR ISLANDS",
        "age": 73.0,
        "education_level": "Graduate",
        "self_profession": "Social Service",
        "declared_assets_2024": 27439170.0,      # "Rs 2,74,39,170"
        "declared_liabilities_2024": 302788.0,   # "Rs 3,02,788"
        "criminal_cases_2024": 0.0,              # "No criminal cases"
        "asset_history": {
            2004: 1250619.0,
            2009: 1241034.0,
            2014: 5658980.0,
        },
    },
    "myneta_many_cases.html": {
        # https://www.myneta.info/LokSabha2024/candidate.php?candidate_id=2275
        # THE REGRESSION CASE. Page reads "Number of Criminal Cases: 88".
        "name": "Adv. Dean Kuriakose",
        "party": "INC",
        "constituency": "IDUKKI",
        "region": "KERALA",
        "age": 42.0,
        "education_level": "Post Graduate",
        "self_profession": "Advocate",
        "declared_assets_2024": 20797763.0,      # "Rs 2,07,97,763"
        "declared_liabilities_2024": 3619970.0,  # "Rs 36,19,970"
        "criminal_cases_2024": 88.0,             # <-- was silently missing
        "asset_history": {
            2019: 13395011.0,                    # Lok Sabha 2019, 204 cases
        },
    },
}


def claims_from(extractor, html: str) -> tuple[list, list]:
    """Run the parser over a fixture and split its output."""
    items = list(extractor._parse(html, sid=1, url="fixture://test"))
    offices = [i for i in items if type(i).__name__ == "Office"]
    claims = [i for i in items if type(i).__name__ == "Claim"]
    return offices, claims


def one(claims, predicate, as_of=None):
    hits = [c for c in claims if c.predicate == predicate
            and (as_of is None or c.as_of == as_of)]
    return hits[0] if hits else None


def test_myneta(ex: MyNeta) -> None:
    print("\n[MyNeta] Indian candidate affidavits")
    for fname, want in MYNETA_EXPECTED.items():
        path = FIX / fname
        if not path.exists():
            print(f"  SKIP  {fname} (missing fixture)")
            continue
        print(f"\n  --- {fname} ---")
        html = path.read_bytes().decode("utf-8", errors="replace")
        offices, claims = claims_from(ex, html)

        o = offices[0] if offices else None
        check(f"{fname}: name", o.person_name if o else None, want["name"])
        check(f"{fname}: party", o.party if o else None, want["party"])
        check(f"{fname}: constituency", o.constituency if o else None, want["constituency"])
        check(f"{fname}: region", o.region if o else None, want["region"])

        age = one(claims, "age")
        check(f"{fname}: age", age.value_num if age else None, want["age"])

        edu = one(claims, "education_level")
        check(f"{fname}: education", edu.value_text if edu else None, want["education_level"])

        prof = one(claims, "self_profession")
        check(f"{fname}: profession", prof.value_text if prof else None,
              want["self_profession"])

        a = one(claims, "declared_assets", "2024-01-01")
        check(f"{fname}: assets 2024", a.value_num if a else None,
              want["declared_assets_2024"])

        li = one(claims, "declared_liabilities", "2024-01-01")
        check(f"{fname}: liabilities 2024", li.value_num if li else None,
              want["declared_liabilities_2024"])

        cc = one(claims, "criminal_cases_declared", "2024-01-01")
        check(f"{fname}: criminal cases 2024", cc.value_num if cc else None,
              want["criminal_cases_2024"])

        hist = {
            int(c.as_of[:4]): c.value_num
            for c in claims
            if c.predicate == "declared_assets" and c.as_of != "2024-01-01"
        }
        check(f"{fname}: prior-election asset history", hist, want["asset_history"])


def test_money_parsing() -> None:
    print("\n[units] rupee and sterling parsing")
    # Indian digit grouping is 2,2,3 - not 3,3,3
    check("Rs 8,05,85,824 -> 80585824", rupees("Rs 8,05,85,824"), 80585824.0)
    check("nbsp separator", rupees("Rs 1,33,95,011"), 13395011.0)
    check("'Nil' is absent, not zero", rupees("Nil"), None)
    check("empty string", rupees(""), None)
    check("no amount present", rupees("Liabilities:"), None)
    check("GBP with pence", sterling("Payment received - £18,450.00"), 18450.0)
    check("GBP no pence", sterling("£5,000"), 5000.0)
    check("GBP absent", sterling("Legal services - Janes Solicitors"), None)


def test_uk(con) -> None:
    print("\n[UK Parliament] register of financial interests")
    path = FIX / "uk_interests.json"
    if not path.exists():
        print("  SKIP  uk_interests.json (missing fixture)")
        return
    payload = json.loads(path.read_text(encoding="utf-8"))
    items = payload["items"]

    # Hand-read from the fixture: every item has a summary and a category, and
    # only some carry a monetary figure.
    with_money = [i for i in items if "£" in (i.get("summary") or "")]
    check("fixture has items", len(items) > 0, True)
    check("some items carry a £ amount", len(with_money) > 0, True)

    ex = UKParliament(con, delay=0)
    claims = list(ex._interests(172, "Ms Diane Abbott", "Hackney"))
    earnings = [c for c in claims if c.predicate == "outside_earnings"]
    interests = [c for c in claims if c.predicate == "registered_interest"]

    check("every £ item becomes outside_earnings", len(earnings), len(with_money))
    check("every item becomes exactly one claim", len(claims), len(items))
    check("non-money items become registered_interest",
          len(interests), len(items) - len(with_money))
    check("earnings carry GBP currency",
          all(c.currency == "GBP" for c in earnings), True)
    check("earnings never carry a rupee symbol by default",
          all(c.currency != "INR" for c in earnings), True)
    check("free-text parsing is flagged below full confidence",
          all(c.confidence < 1.0 for c in earnings), True)
    check("every claim is dated", all(c.as_of for c in claims), True)

    # A UK payment is a flow. It must never be emitted as an asset stock.
    check("no UK claim is declared_assets",
          any(c.predicate == "declared_assets" for c in claims), False)


def test_corroboration_dates() -> None:
    """The three date bugs that took cross-source agreement from 97.5% to 57.3%.

    Each of these only appears once a person has more than one claim from the
    same publisher, which is why none of them showed up until the 2019
    affidavits and the 2026 witnesses were added. They are pinned here because
    the same mistake - comparing values without their reference date - has now
    been made twice.
    """
    from etl.corroborate import (
        birth_year,
        learn_party_aliases,
        party_key,
    )

    # 1. An age is a fact about a DATE. A man who is 50 in 2019, 55 in 2024 and
    #    58 in 2026 has had birthdays, not a disagreement.
    born = [birth_year(50, "2019-01-01"), birth_year(55, "2024-01-01"),
            birth_year(58, "2026-01-01")]
    check("ages across years resolve to one birth year",
          max(born) - min(born) <= 3, True)
    check("a genuinely different birth year is still caught",
          abs(birth_year(56, "2024-01-01") - birth_year(65, "2024-01-01")) > 3, True)

    # 2. Two spellings seen for one person in one year are the same party.
    aliases = learn_party_aliases({
        1: {("BJP", "2024-01-01"), ("Bharatiya Janata Party", "2024-01-01")},
        2: {("TDP", "2024-01-01"), ("Telugu Desam Party", "2024-01-01")},
        3: {("JD(U)", "2024-01-01"), ("Janata Dal (United)", "2024-01-01")},
    })
    check("BJP is the Bharatiya Janata Party",
          party_key("BJP", aliases) == party_key("Bharatiya Janata Party", aliases),
          True)
    check("TDP is the Telugu Desam Party",
          party_key("TDP", aliases) == party_key("Telugu Desam Party", aliases), True)
    check("JD(U) survives punctuation stripping",
          party_key("JD(U)", aliases) == party_key("Janata Dal (United)", aliases),
          True)

    # Abbreviations skip the small words, and absorb an acronym whole.
    hard = learn_party_aliases({
        4: {("CPI(ML)(L)", "2024-01-01"),
            ("Communist Party of India (Marxist-Leninist) (Liberation)",
             "2024-01-01")},
        5: {("YSRCP", "2024-01-01"),
            ("Yuvajana Sramika Rythu Congress Party", "2024-01-01")},
    })
    check("'of' contributes no initial (CPI(ML)(L), not CPOIML(L))",
          party_key("CPI(ML)(L)", hard)
          == party_key("Communist Party of India (Marxist-Leninist) (Liberation)",
                       hard),
          True)
    check("an en dash reads the same as a hyphen",
          party_key("CPI(ML)(L)", hard)
          == party_key("Communist Party of India (Marxist–Leninist) Liberation",
                       hard),
          True)
    # "YSR" is itself three initials, so YSR Congress Party is YSRCP, not YCP.
    # This spelling appears only in Wikidata, never beside another, so it is
    # reached through its own abbreviation rather than through co-occurrence.
    check("an embedded acronym contributes all its letters",
          party_key("YSR Congress Party", hard) == party_key("YSRCP", hard), True)

    # A party SPLIT is not a spelling variant. The LJP divided in 2021, and the
    # faction name is the whole difference between the two parties.
    check("Lok Janshakti Party (Ram Vilas) is not Lok Janshakti Party",
          party_key("Lok Janshakti Party (Ram Vilas)", hard)
          == party_key("Lok Janshakti Party", hard),
          False)

    # 3. THE IMPORTANT ONE. A defector reports one party in 2019 and another in
    #    2024. That is a change of party, and must never be learned as a change
    #    of NAME - one switcher poisoning this map moved 1,008 people onto the
    #    wrong canonical party.
    poisoned = learn_party_aliases({
        1: {("BJP", "2024-01-01"), ("Bharatiya Janata Party", "2024-01-01")},
        9: {("Indian National Congress", "2019-01-01"), ("BJP", "2024-01-01")},
    })
    check("a defection does not merge the two parties",
          party_key("Indian National Congress", poisoned) == party_key("BJP", poisoned),
          False)
    check("the defector does not break the real alias either",
          party_key("BJP", poisoned) == party_key("Bharatiya Janata Party", poisoned),
          True)

    # Even reported in the SAME year - a floor-crossing - the structural check
    # refuses, because "INC" is not an abbreviation of "Bharatiya Janata Party".
    same_year = learn_party_aliases({
        7: {("Indian National Congress", "2024-01-01"), ("BJP", "2024-01-01")},
    })
    check("same-year defection is still not a synonym",
          party_key("Indian National Congress", same_year) == party_key("BJP", same_year),
          False)


def test_seat_keys() -> None:
    """One seat must stay one seat, and two seats must stay two - in 3 countries.

    The rule that stripped a bare "SC"/"ST" reservation marker reached the repo
    with its `\b` escapes eaten into literal backspace bytes, so it silently
    matched nothing. Repairing it would have been worse than leaving it broken:
    it would have renamed "St Albans" and collapsed South Carolina. These cases
    are pinned because the fix is a DELETION, and a future reader who sees the
    missing rule may be tempted to put it back.
    """
    from etl.export_people import _same_seat, _seat_key

    def same(a, b):
        return _same_seat(_seat_key(a), _seat_key(b))

    # India: the reservation marker is always parenthesised, and carries no
    # identifying information.
    check("ARAKU(ST) is ARAKU", same("ARAKU(ST)", "ARAKU"), True)
    check("NELLORE(SC) is NELLORE", same("NELLORE(SC)", "NELLORE"), True)
    check("truncation is the same seat",
          same("NAINITAL-UDHAM SINGH NAGAR", "NAINITAL UDHAM SINGH NAG."), True)
    check("a one-letter spelling variant is the same seat",
          same("BARAMULLA", "BARAMULLAH"), True)
    check("two real seats stay two", same("WAYANAD", "RAE BARELI"), False)
    check("EAST DELHI keeps its E-A-S-T", _seat_key("EAST DELHI"), "eastdelhi")

    # United Kingdom: "St" is part of the name, not a marker.
    check("St Albans is not Albans", _seat_key("St Albans"), "stalbans")
    check("two St seats stay two", same("St Albans", "St Ives"), False)

    # United States: the district NUMBER is the seat.
    check("SC-02 and SC-06 are two seats", same("SC-02", "SC-06"), False)
    check("a district number survives normalising", _seat_key("SC-06"), "sc06")


def test_url_redaction() -> None:
    """A credential must never be written down; a field selector must survive.

    The URL of every request is published - stored in `sources.url`, exported as
    `src_url` on every claim, and rendered as a link on the live site. An API
    that authenticates with `?key=` would therefore have put the operator's
    Google key into 2,196 person files and a public git history.

    Redacting on the parameter NAME alone is not the fix, and that mistake was
    caught by the scanner it was paired with: MPLADS asks for a metric with
    `key=Allocated Limit for Hon'ble MPs`, where `key` selects a field and is
    the whole meaning of the request. Masking it would have destroyed the
    archive identity of every MPLADS document and collapsed distinct queries
    into one colliding URL. So the VALUE decides, and both cases are pinned.
    """
    from ingest.archive import is_secret, redact

    mplads = ("https://mplads.mospi.gov.in/rest/PreLoginDashboardData/"
              "getTilesReportData?combo=0%2C0%2C0%2C2"
              "&key=Allocated+Limit+for+Hon%27ble+MPs")
    factcheck = ("https://factchecktools.googleapis.com/v1alpha1/claims:search"
                 "?key=AIzaSyA1b2C3d4E5f6G7h8I9j0K1l2M3n4O5p6Q"
                 "&pageSize=10&query=Rahul+Gandhi")

    check("a Google API key is masked", "AIzaSyA1b2C3d4E5f6G7h8I9j0K1l2M3n4O5p6Q"
          not in redact(factcheck), True)
    check("the rest of the request survives redaction",
          "query=Rahul+Gandhi" in redact(factcheck), True)
    check("MPLADS' key= field selector is NOT a credential",
          redact(mplads), mplads)
    check("a URL with no secret is returned byte-identical",
          redact("https://www.myneta.info/LokSabha2024/index.php?action=summary"),
          "https://www.myneta.info/LokSabha2024/index.php?action=summary")

    # Names that are unambiguous are redacted whatever they hold; ambiguous ones
    # are judged on shape, and a space is what gives a human-readable value away.
    check("api_key is a credential regardless of value",
          is_secret("api_key", "x"), True)
    check("a value containing spaces is not a credential",
          is_secret("key", "Allocated Limit for Hon'ble MPs"), False)
    check("a long opaque value under an ambiguous name is a credential",
          is_secret("key", "AIzaSyA1b2C3d4E5f6G7h8I9j0K1l2M3n4O5p6Q"), True)
    check("a short token is not assumed to be a credential",
          is_secret("token", "abc"), False)


def main() -> int:
    tmp = ROOT / "data" / "processed" / "_parsertest.db"
    if tmp.exists():
        tmp.unlink()
    con = connect(tmp)
    ex = MyNeta(con, delay=0)

    test_myneta(ex)
    test_money_parsing()
    test_uk(con)
    test_corroboration_dates()
    test_seat_keys()
    test_url_redaction()

    con.close()
    tmp.unlink(missing_ok=True)
    for suffix in ("-wal", "-shm"):
        Path(str(tmp) + suffix).unlink(missing_ok=True)

    print()
    if failures:
        print(f"FAILED {len(failures)} check(s):")
        for f in failures:
            print(f"  - {f}")
        return 1
    print("All parser checks passed.\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
