"""Parser tests against real archived pages.

    python tests/test_parsers.py

WHY THESE EXIST
---------------
37% of claims in the store were parsed heuristically out of summary tables and
free text. Nothing checked that the parser read them correctly, and the first
thing a careful read of four pages turned up was that 250 of 544 Indian MPs were
silently missing their declared criminal-case count: the "Crime-O-Meter" block
writes the number AFTER the words ("Number of Criminal Cases: 88") and the regex
only matched a leading-number form that never appears on the page. Members with
zero cases parsed fine; every member WITH cases recorded no data at all.

That is the worst possible direction for an error in a tool like this - it made
the dataset look cleaner than reality - and it survived a full 543-member harvest
without a single visible symptom.

THE RULE FOR THIS FILE
----------------------
Expected values are read BY EYE from the rendered page and written down here by
hand. They are never generated by running the parser. A test whose expectations
came from the code under test proves only that the code is deterministic.

Each fixture is a real archived document, byte-identical to what the harvester
saw, so these tests also pin the page layouts we depend on: if MyNeta restructures
its pages, a fresh fixture will fail against these hand-read values and tell us.
"""

from __future__ import annotations

import json
import sqlite3
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from ingest.extractors.myneta import MyNeta, rupees  # noqa: E402
from ingest.extractors.ukparliament import UKParliament, sterling  # noqa: E402
from ingest.schema import connect  # noqa: E402

FIX = Path(__file__).parent / "fixtures"

failures: list[str] = []


def check(name: str, got, want) -> None:
    ok = got == want
    print(f"  {'PASS' if ok else 'FAIL'}  {name}"
          + ("" if ok else f"\n          got  {got!r}\n          want {want!r}"))
    if not ok:
        failures.append(name)


# ---------------------------------------------------------------------------
# Hand-read expectations. Every value below was read off the rendered page.
# ---------------------------------------------------------------------------

MYNETA_EXPECTED = {
    "myneta_multi_election.html": {
        # https://www.myneta.info/LokSabha2024/candidate.php?candidate_id=476
        "name": "Amraram",
        "party": "CPI(M)",
        "constituency": "SIKAR",
        "region": "RAJASTHAN",
        "age": 68.0,
        "education_level": "Post Graduate",
        "self_profession": "Agriculture Work and Pension of former MLA",
        "declared_assets_2024": 4050109.0,       # "Assets: Rs 40,50,109"
        "declared_liabilities_2024": None,       # page says "Liabilities: Nil"
        "criminal_cases_2024": 0.0,              # "No criminal cases"
        # "Other Elections" table, read row by row
        "asset_history": {
            2008: 1734392.0,   # Rajasthan 2008   Rs17,34,392
            2009: 1902684.0,   # Lok Sabha 2009   Rs19,02,684
            2013: 4084479.0,   # Rajasthan 2013   Rs40,84,479
            2014: 4681929.0,   # Loksabha 2014    Rs46,81,929
            2018: 4353653.0,   # Rajasthan 2018   Rs43,53,653
            2019: 4444641.0,   # Lok Sabha 2019   Rs44,44,641
            2023: 3842432.0,   # Rajasthan 2023   Rs38,42,432
        },
    },
    "myneta_no_cases.html": {
        # https://www.myneta.info/LokSabha2024/candidate.php?candidate_id=17
        "name": "Bishnu Pada Ray",
        "party": "BJP",
        "constituency": "ANDAMAN AND NICOBAR ISLANDS",
        "region": "ANDAMAN AND NICOBAR ISLANDS",
        "age": 73.0,
        "education_level": "Graduate",
        "self_profession": "Social Service",
        "declared_assets_2024": 27439170.0,      # "Rs 2,74,39,170"
        "declared_liabilities_2024": 302788.0,   # "Rs 3,02,788"
        "criminal_cases_2024": 0.0,              # "No criminal cases"
        "asset_history": {
            2004: 1250619.0,
            2009: 1241034.0,
            2014: 5658980.0,
        },
    },
    "myneta_many_cases.html": {
        # https://www.myneta.info/LokSabha2024/candidate.php?candidate_id=2275
        # THE REGRESSION CASE. Page reads "Number of Criminal Cases: 88".
        "name": "Adv. Dean Kuriakose",
        "party": "INC",
        "constituency": "IDUKKI",
        "region": "KERALA",
        "age": 42.0,
        "education_level": "Post Graduate",
        "self_profession": "Advocate",
        "declared_assets_2024": 20797763.0,      # "Rs 2,07,97,763"
        "declared_liabilities_2024": 3619970.0,  # "Rs 36,19,970"
        "criminal_cases_2024": 88.0,             # <-- was silently missing
        "asset_history": {
            2019: 13395011.0,                    # Lok Sabha 2019, 204 cases
        },
    },
}


def claims_from(extractor, html: str) -> tuple[list, list]:
    """Run the parser over a fixture and split its output."""
    items = list(extractor._parse(html, sid=1, url="fixture://test"))
    offices = [i for i in items if type(i).__name__ == "Office"]
    claims = [i for i in items if type(i).__name__ == "Claim"]
    return offices, claims


def one(claims, predicate, as_of=None):
    hits = [c for c in claims if c.predicate == predicate
            and (as_of is None or c.as_of == as_of)]
    return hits[0] if hits else None


def test_myneta(ex: MyNeta) -> None:
    print("\n[MyNeta] Indian candidate affidavits")
    for fname, want in MYNETA_EXPECTED.items():
        path = FIX / fname
        if not path.exists():
            print(f"  SKIP  {fname} (missing fixture)")
            continue
        print(f"\n  --- {fname} ---")
        html = path.read_bytes().decode("utf-8", errors="replace")
        offices, claims = claims_from(ex, html)

        o = offices[0] if offices else None
        check(f"{fname}: name", o.person_name if o else None, want["name"])
        check(f"{fname}: party", o.party if o else None, want["party"])
        check(f"{fname}: constituency", o.constituency if o else None, want["constituency"])
        check(f"{fname}: region", o.region if o else None, want["region"])

        age = one(claims, "age")
        check(f"{fname}: age", age.value_num if age else None, want["age"])

        edu = one(claims, "education_level")
        check(f"{fname}: education", edu.value_text if edu else None, want["education_level"])

        prof = one(claims, "self_profession")
        check(f"{fname}: profession", prof.value_text if prof else None,
              want["self_profession"])

        a = one(claims, "declared_assets", "2024-01-01")
        check(f"{fname}: assets 2024", a.value_num if a else None,
              want["declared_assets_2024"])

        li = one(claims, "declared_liabilities", "2024-01-01")
        check(f"{fname}: liabilities 2024", li.value_num if li else None,
              want["declared_liabilities_2024"])

        cc = one(claims, "criminal_cases_declared", "2024-01-01")
        check(f"{fname}: criminal cases 2024", cc.value_num if cc else None,
              want["criminal_cases_2024"])

        hist = {
            int(c.as_of[:4]): c.value_num
            for c in claims
            if c.predicate == "declared_assets" and c.as_of != "2024-01-01"
        }
        check(f"{fname}: prior-election asset history", hist, want["asset_history"])


def test_money_parsing() -> None:
    print("\n[units] rupee and sterling parsing")
    # Indian digit grouping is 2,2,3 - not 3,3,3
    check("Rs 8,05,85,824 -> 80585824", rupees("Rs 8,05,85,824"), 80585824.0)
    check("nbsp separator", rupees("Rs 1,33,95,011"), 13395011.0)
    check("'Nil' is absent, not zero", rupees("Nil"), None)
    check("empty string", rupees(""), None)
    check("no amount present", rupees("Liabilities:"), None)
    check("GBP with pence", sterling("Payment received - £18,450.00"), 18450.0)
    check("GBP no pence", sterling("£5,000"), 5000.0)
    check("GBP absent", sterling("Legal services - Janes Solicitors"), None)


def test_uk(con) -> None:
    print("\n[UK Parliament] register of financial interests")
    path = FIX / "uk_interests.json"
    if not path.exists():
        print("  SKIP  uk_interests.json (missing fixture)")
        return
    payload = json.loads(path.read_text(encoding="utf-8"))
    items = payload["items"]

    # Hand-read from the fixture: every item has a summary and a category, and
    # only some carry a monetary figure.
    with_money = [i for i in items if "£" in (i.get("summary") or "")]
    check("fixture has items", len(items) > 0, True)
    check("some items carry a £ amount", len(with_money) > 0, True)

    ex = UKParliament(con, delay=0)
    claims = list(ex._interests(172, "Ms Diane Abbott", "Hackney"))
    earnings = [c for c in claims if c.predicate == "outside_earnings"]
    interests = [c for c in claims if c.predicate == "registered_interest"]

    check("every £ item becomes outside_earnings", len(earnings), len(with_money))
    check("every item becomes exactly one claim", len(claims), len(items))
    check("non-money items become registered_interest",
          len(interests), len(items) - len(with_money))
    check("earnings carry GBP currency",
          all(c.currency == "GBP" for c in earnings), True)
    check("earnings never carry a rupee symbol by default",
          all(c.currency != "INR" for c in earnings), True)
    check("free-text parsing is flagged below full confidence",
          all(c.confidence < 1.0 for c in earnings), True)
    check("every claim is dated", all(c.as_of for c in claims), True)

    # A UK payment is a flow. It must never be emitted as an asset stock.
    check("no UK claim is declared_assets",
          any(c.predicate == "declared_assets" for c in claims), False)


def main() -> int:
    tmp = ROOT / "data" / "processed" / "_parsertest.db"
    if tmp.exists():
        tmp.unlink()
    con = connect(tmp)
    ex = MyNeta(con, delay=0)

    test_myneta(ex)
    test_money_parsing()
    test_uk(con)

    con.close()
    tmp.unlink(missing_ok=True)
    for suffix in ("-wal", "-shm"):
        Path(str(tmp) + suffix).unlink(missing_ok=True)

    print()
    if failures:
        print(f"FAILED {len(failures)} check(s):")
        for f in failures:
            print(f"  - {f}")
        return 1
    print("All parser checks passed.\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
